version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./DarkShard/Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes: 
      - './DarkShard/dist:/dist'